//! Golden pins for the pre-contract writers and reader.
//!
//! `tests/golden/*.pcx` were generated by this same file from the crate
//! as it stood before the IMAGE_CRATE_API migration (round 467), with
//! `PCX_GOLDEN_WRITE=1`. Every deprecated `encode_pcx_*` wrapper must
//! still produce those exact bytes, and the flatten reader must still
//! produce the pinned `.rgba` for each of them. Re-generating the
//! fixtures is a deliberate act, never part of a normal test run.

#![allow(deprecated)]

use std::path::PathBuf;

use oxideav_pcx::*;

fn golden_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden")
}

/// Deterministic byte stream (LCG) so the fixtures are reproducible.
fn seeded(len: usize, mut seed: u32) -> Vec<u8> {
    let mut out = Vec::with_capacity(len);
    for _ in 0..len {
        seed = seed.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        out.push((seed >> 24) as u8);
    }
    out
}

const W: u16 = 37;
const H: u16 = 11;
const N: usize = W as usize * H as usize;

fn rgb_many() -> Vec<u8> {
    seeded(N * 3, 7)
}

fn rgb_from_palette(palette: &[[u8; 3]], seed: u32) -> Vec<u8> {
    let picks = seeded(N, seed);
    let mut out = Vec::with_capacity(N * 3);
    for p in picks {
        out.extend_from_slice(&palette[p as usize % palette.len()]);
    }
    out
}

fn indices(max: u8, seed: u32) -> Vec<u8> {
    seeded(N, seed)
        .into_iter()
        .map(|b| (u16::from(b) % (u16::from(max) + 1)) as u8)
        .collect()
}

fn pal768() -> Vec<u8> {
    seeded(768, 99)
}

fn pal48() -> Vec<u8> {
    let mut p = seeded(48, 5);
    // Keep the all-zero sentinel away.
    p[0] = 0x12;
    p
}

fn image(
    rgb: &[u8],
    dpi: Option<(u16, u16)>,
    win: Option<(u16, u16)>,
    scr: Option<(u16, u16)>,
) -> PcxImage {
    PcxImage::from_rgb8(u32::from(W), u32::from(H), rgb.to_vec())
        .unwrap()
        .with_dpi(dpi)
        .with_window_origin(win)
        .with_screen_size(scr)
}

/// Every pre-contract writer with a fixed input, by fixture name.
#[allow(clippy::vec_init_then_push)]
fn cases() -> Vec<(&'static str, Vec<u8>)> {
    let primaries: Vec<[u8; 3]> = (0..8u8)
        .map(|i| {
            [
                if i & 1 != 0 { 0xFF } else { 0 },
                if i & 2 != 0 { 0xFF } else { 0 },
                if i & 4 != 0 { 0xFF } else { 0 },
            ]
        })
        .collect();
    let grey_pal: Vec<[u8; 3]> = [0x00u8, 0x10, 0x80, 0xFE]
        .iter()
        .map(|&g| [g, g, g])
        .collect();
    let bw: Vec<[u8; 3]> = vec![[0, 0, 0], [0xFF, 0xFF, 0xFF]];
    // CGA palette 1 bright with background 1 (blue): cyan / magenta / white.
    let cga: Vec<[u8; 3]> = vec![
        [0x00, 0x00, 0xAA],
        [0x55, 0xFF, 0xFF],
        [0xFF, 0x55, 0xFF],
        [0xFF, 0xFF, 0xFF],
    ];
    let sixteen: Vec<[u8; 3]> = seeded(48, 31)
        .chunks_exact(3)
        .map(|c| [c[0], c[1], c[2]])
        .collect();
    let two_hundred: Vec<[u8; 3]> = seeded(600, 32)
        .chunks_exact(3)
        .map(|c| [c[0], c[1], c[2]])
        .collect();

    let many = rgb_many();
    let dpi = (300u16, 150u16);
    let win = (17u16, 9u16);
    let scr = (640u16, 480u16);
    let mut v: Vec<(&'static str, Vec<u8>)> = Vec::new();

    v.push((
        "8bpp_indexed",
        encode_pcx_8bpp_indexed(W, H, &indices(255, 1), &pal768()).unwrap(),
    ));
    v.push(("24bpp", encode_pcx_24bpp(W, H, &many).unwrap()));
    v.push((
        "1bpp_mono",
        encode_pcx_1bpp_mono(W, H, &indices(1, 2)).unwrap(),
    ));
    v.push((
        "1bpp_3planes_ega_rgb",
        encode_pcx_1bpp_3planes_ega_rgb(W, H, &rgb_from_palette(&primaries, 3)).unwrap(),
    ));
    v.push((
        "1bpp_3planes_ega_rgb_threshold",
        encode_pcx_1bpp_3planes_ega_rgb(W, H, &many).unwrap(),
    ));
    v.push((
        "1bpp_4planes_ega",
        encode_pcx_1bpp_4planes_ega(W, H, &indices(15, 4), &pal48()).unwrap(),
    ));
    v.push((
        "4bpp_packed",
        encode_pcx_4bpp_packed(W, H, &indices(15, 4), &pal48()).unwrap(),
    ));
    v.push((
        "2bpp_cga",
        encode_pcx_2bpp_cga(W, H, &indices(3, 6), 0x60, 1).unwrap(),
    ));
    v.push((
        "2bpp_cga_mono",
        encode_pcx_2bpp_cga(W, H, &indices(3, 6), 0xA0, 0).unwrap(),
    ));
    v.push((
        "2bpp_cga_cpi",
        encode_pcx_2bpp_cga_cpi(W, H, &indices(3, 6), Pcx2bppCgaCpi::from_byte19(0x40), 3).unwrap(),
    ));
    v.push((
        "1bpp_2planes_cga",
        encode_pcx_1bpp_2planes_cga(W, H, &indices(3, 6), 0x20, 2).unwrap(),
    ));
    let composite: Vec<u16> = seeded(N * 2, 8)
        .chunks_exact(2)
        .map(|c| u16::from_le_bytes([c[0], c[1]]))
        .collect();
    v.push((
        "4bpp_4planes",
        encode_pcx_4bpp_4planes(W, H, &composite).unwrap(),
    ));
    v.push((
        "8bpp_grayscale",
        encode_pcx_8bpp_grayscale(W, H, &indices(255, 9)).unwrap(),
    ));
    v.push((
        "24bpp_window",
        encode_pcx_24bpp_window(win.0, win.1, W, H, &many).unwrap(),
    ));
    v.push(("24bpp_dpi", encode_pcx_24bpp_dpi(W, H, &many, dpi).unwrap()));
    v.push((
        "8bpp_indexed_dpi",
        encode_pcx_8bpp_indexed_dpi(W, H, &indices(255, 1), &pal768(), dpi).unwrap(),
    ));
    v.push((
        "8bpp_grayscale_dpi",
        encode_pcx_8bpp_grayscale_dpi(W, H, &indices(255, 9), dpi).unwrap(),
    ));
    v.push((
        "1bpp_mono_dpi",
        encode_pcx_1bpp_mono_dpi(W, H, &indices(1, 2), dpi).unwrap(),
    ));
    v.push((
        "4bpp_packed_dpi",
        encode_pcx_4bpp_packed_dpi(W, H, &indices(15, 4), &pal48(), dpi).unwrap(),
    ));
    v.push((
        "2bpp_cga_dpi",
        encode_pcx_2bpp_cga_dpi(W, H, &indices(3, 6), 0x60, 1, dpi).unwrap(),
    ));
    v.push((
        "1bpp_2planes_cga_dpi",
        encode_pcx_1bpp_2planes_cga_dpi(W, H, &indices(3, 6), 0x20, 2, dpi).unwrap(),
    ));
    v.push((
        "1bpp_3planes_ega_rgb_dpi",
        encode_pcx_1bpp_3planes_ega_rgb_dpi(W, H, &rgb_from_palette(&primaries, 3), dpi).unwrap(),
    ));
    v.push((
        "1bpp_4planes_ega_dpi",
        encode_pcx_1bpp_4planes_ega_dpi(W, H, &indices(15, 4), &pal48(), dpi).unwrap(),
    ));
    v.push((
        "24bpp_window_dpi",
        encode_pcx_24bpp_window_dpi(win.0, win.1, W, H, &many, dpi).unwrap(),
    ));
    v.push((
        "24bpp_screen",
        encode_pcx_24bpp_screen(W, H, &many, scr).unwrap(),
    ));
    v.push((
        "24bpp_window_dpi_screen",
        encode_pcx_24bpp_window_dpi_screen(win.0, win.1, W, H, &many, dpi, scr).unwrap(),
    ));
    // `encode_pcx_24bpp_image` across the eight metadata combinations.
    for (i, (d, w, s)) in [
        (None, None, None),
        (Some(dpi), None, None),
        (None, Some(win), None),
        (None, None, Some(scr)),
        (Some(dpi), Some(win), None),
        (Some(dpi), None, Some(scr)),
        (None, Some(win), Some(scr)),
        (Some(dpi), Some(win), Some(scr)),
    ]
    .into_iter()
    .enumerate()
    {
        let name: &'static str = Box::leak(format!("24bpp_image_{i}").into_boxed_str());
        v.push((
            name,
            encode_pcx_24bpp_image(&image(&many, d, w, s)).unwrap(),
        ));
    }
    // The compact ladder, one input per rung.
    let rungs: Vec<(&'static str, Vec<u8>)> = vec![
        ("auto_mono", rgb_from_palette(&bw, 11)),
        ("auto_cga", rgb_from_palette(&cga, 12)),
        ("auto_ega_rgb", rgb_from_palette(&primaries, 13)),
        ("auto_gray", rgb_from_palette(&grey_pal, 14)),
        ("auto_sixteen", rgb_from_palette(&sixteen, 15)),
        ("auto_two_hundred", rgb_from_palette(&two_hundred, 16)),
        ("auto_many", many.clone()),
    ];
    for (name, rgb) in &rungs {
        let (bytes, _mode) = encode_pcx_rgb_auto(W, H, rgb).unwrap();
        v.push((name, bytes));
        let name_img: &'static str = Box::leak(format!("{name}_image_dpi").into_boxed_str());
        let (bytes, _mode) = encode_pcx_image_auto(&image(rgb, Some(dpi), None, None)).unwrap();
        v.push((name_img, bytes));
        let name_win: &'static str = Box::leak(format!("{name}_image_win").into_boxed_str());
        let (bytes, _mode) = encode_pcx_image_auto(&image(rgb, None, Some(win), None)).unwrap();
        v.push((name_win, bytes));
    }
    // Caller-palette ladder: ≤ 16 entries, > 16 entries, all-zero table,
    // and indices beyond the 4-bit range.
    v.push((
        "indexed_auto_small",
        encode_pcx_indexed_auto(W, H, &indices(5, 21), &seeded(18, 22))
            .unwrap()
            .0,
    ));
    v.push((
        "indexed_auto_large",
        encode_pcx_indexed_auto(W, H, &indices(40, 23), &seeded(150, 24))
            .unwrap()
            .0,
    ));
    v.push((
        "indexed_auto_zero",
        encode_pcx_indexed_auto(W, H, &indices(1, 25), &[0u8; 6])
            .unwrap()
            .0,
    ));
    v.push((
        "indexed_auto_wide",
        encode_pcx_indexed_auto(W, H, &indices(200, 26), &seeded(9, 27))
            .unwrap()
            .0,
    ));
    // DCX bundle of three pages.
    let pages = vec![
        encode_pcx_24bpp(W, H, &many).unwrap(),
        encode_pcx_1bpp_mono(W, H, &indices(1, 2)).unwrap(),
        encode_pcx_8bpp_indexed(W, H, &indices(255, 1), &pal768()).unwrap(),
    ];
    v.push(("dcx_three_pages", encode_dcx(&pages).unwrap()));
    v
}

/// The legacy flatten of a fixture: packed RGBA, or `None` where the old
/// reader rejected the geometry (the `(4, 4)` composite mode).
fn legacy_rgba(name: &str, bytes: &[u8]) -> Option<Vec<u8>> {
    if name == "dcx_three_pages" {
        let d = parse_dcx(bytes).unwrap();
        let mut out = Vec::new();
        for p in d.pages {
            out.extend_from_slice(p.data());
        }
        return Some(out);
    }
    parse_pcx(bytes).ok().map(|img| img.data().to_vec())
}

#[test]
fn pre_contract_writers_and_reader_match_the_goldens() {
    let dir = golden_dir();
    let write = std::env::var_os("PCX_GOLDEN_WRITE").is_some();
    if write {
        std::fs::create_dir_all(&dir).unwrap();
    }
    let mut checked = 0;
    for (name, bytes) in cases() {
        let pcx = dir.join(format!("{name}.pcx"));
        let rgba = dir.join(format!("{name}.rgba"));
        let flat = legacy_rgba(name, &bytes);
        if write {
            std::fs::write(&pcx, &bytes).unwrap();
            if let Some(f) = &flat {
                std::fs::write(&rgba, f).unwrap();
            }
            continue;
        }
        let want = std::fs::read(&pcx).unwrap_or_else(|e| panic!("{name}.pcx: {e}"));
        assert!(
            want == bytes,
            "{name}: writer output drifted from the golden"
        );
        if let Some(f) = flat {
            let want = std::fs::read(&rgba).unwrap_or_else(|e| panic!("{name}.rgba: {e}"));
            assert!(want == f, "{name}: legacy flatten drifted from the golden");
        } else {
            assert!(
                !rgba.exists(),
                "{name}: the golden has an .rgba but the reader now rejects it"
            );
        }
        checked += 1;
    }
    if !write {
        assert!(checked >= 60, "golden set unexpectedly small: {checked}");
    }
}
